### ISSUE TITLE
这个服务器运行后但是打不开摄像头

### ISSUE THREAD

**Issue by shenshihao520** [linsir6/webRTC-android-demo-and-Server#1]

**Comment by linsir6** [comment]
是手机的摄像头启动不了，还是浏览器的摄像头，如果要是手机的摄像头，可以看一下是不是权限问题，因为6.0之后的摄像头权限属于危险权限，需要动态申请，要是浏览器，需要检查一下左上角是否有它的权限，浏览器要用谷歌浏览器

**Comment by shenshihao520** [comment]
那这个webRTC可以实现android - android 间的视频聊天吗

**Comment by linsir6** [comment]
可以的，往笨了说，可以调整一下房间里面最多的人数，然后两个手机加入同一个房间，然后由网页端发起申请，三个人就可以聊天了，也可以更开一下程序，可以看一下我项目第一个的笔记，了解一下webRTC建立链接的过程，然后稍微改一下程序。

**Comment by shenshihao520** [comment]
太感谢了，弱弱的问您一句，笔记在哪

**Comment by linsir6** [comment]
https://github.com/linsir6/Android-Notes   这里面有个 webRTC的笔记，你可以先写着，遇到问题，随时问～

**Comment by shenshihao520** [comment]
软网环境  视频卡顿，做提示或者直接断开连接，这块儿有做过吗，求教

**Comment by linsir6** [comment]
并没有，我在流媒体方面是个小学生，就是一时兴起写了点小程序

**Comment by shenshihao520** [comment]
好吧。谢谢
