### ISSUE TITLE
ICE Disconnected

### ISSUE THREAD

**Issue by orangeai** [linsir6/webRTC-android-demo-and-Server#2]
我也是參考pchab的Android RTC
但我會遇到成功通話後Ice connection 變成DISCONNECTED 可能幾秒鐘至幾分鐘
或是有時候會進入FAILED的狀態
請問你有遇到嗎?

**Comment by linsir6** [comment]
遇到过，我也不太清楚为什么。 就是经常连着 连着 视频就停下了。。。 我分析应该是代码中，控制链接状态的逻辑不对，应该不是真的failed了。这个可能我也帮不上您。

**Comment by cs83312** [comment]
hi
我的解法是當觸發disconnect,
就重新建立ice的連線
