### ISSUE TITLE
请问，能不能实现android对android的功能

### ISSUE THREAD

**Issue by jayslife0** [linsir6/webRTC-android-demo-and-Server#3]

**Comment by linsir6** [comment]
https://github.com/linsir6/webRTC-android-demo-and-Server/issues/1

**Comment by jayslife0** [comment]
ok,谢谢你的回复。还有个关于turnservice的问题想请教一下，在局域网（比如家里同一路由下的2个android 平板）环境下，实现android对android，是不是可以不需要turn service

**Comment by linsir6** [comment]
对的，就不需要打洞了
