### ISSUE TITLE
老哥 请问android 和web视频问题

### ISSUE THREAD

**Issue by ZY6666** [linsir6/webRTC-android-demo-and-Server#9]
老哥 外网服务搭建成功了，浏览器端互相视频语音也可以了，现在有个问题是 android端和网页端建立连接成功后，网页端显示正常，安卓端接受的网页端视频是卡死的，找不到问题出在哪。可以加下QQ么 。Q 390590581

**Comment by Ronrey100** [comment]
是啊，同问方便建群一起探讨吗？Q：2621482946

**Comment by linsir6** [comment]
兄弟们，我能力可能还不如你们呢。。。 我就是 当时在一个公司实习，搞了一小段时间webrtc,不过我当时的老板，非常厉害。  他有一个webrtc的群，我建议你们加他，然后备注加群吧。微信: notedit 。 你们加他，然后备注加webrtc的群就行。我已经不搞webrtc了

**Comment by Ronrey100** [comment]
OK，多谢。刚加了，真巧，跟你们老板之前联系过。
